import type { Metadata } from 'next'
import './globals.css'
import { Poppins as FontSans } from 'next/font/google'

import { cn } from '@/lib/utils'
import AuthProvider from '@/context/session-provider'
import React from 'react'
import { Toaster } from '@/components/ui/sonner'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: ['400', '500', '600', '700', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={cn(
            'min-h-screen w-full bg-background font-sans antialiased flex relative',
            fontSans.variable
          )}
        >
          <Toaster position="top-right" />
          {children}
        </body>
      </html>
    </AuthProvider>
  )
}
